TARGET = PlacementClient
OBJS += ../prot/PlacementController_prot_xdr.o
OBJS += ../prot/PlacementController_prot_clnt.o
OBJS += ../prot/PlacementController_clnt.o
OBJS += PlacementClient.o
OBJS += ../json/jsoncpp.o
LIBS += -lm

include ../common/Makefile.template
include ../prot/Makefile.template
